### ISSUE TITLE
Pre-Trained Model

### ISSUE THREAD

**Issue by arslanfirat** [ycdhqzhiai/Gaze-PFLD#2]
Hi, can you share your pre-trained model, thanks a lot.

**Comment by ycdhqzhiai** [comment]
https://drive.google.com/file/d/1fw63_PCRTFulDf6jgQRCPnKPZHHoYFZ4/view?usp=sharing

**Comment by Cydia2018** [comment]
> https://drive.google.com/file/d/1fw63_PCRTFulDf6jgQRCPnKPZHHoYFZ4/view?usp=sharing

申请下载权限了

**Comment by kimtaehyeong** [comment]
I can't download the current Google Drive link because I don't have permission. Is there a way to download the model?

**Comment by ycdhqzhiai** [comment]
https://drive.google.com/file/d/1fw63_PCRTFulDf6jgQRCPnKPZHHoYFZ4/view?usp=sharing

**Comment by kimtaehyeong** [comment]
Thanks for sharing the link.
However, you do not have permission to download the Google Drive link you shared. Can you give me permission ?
thank you.

**Comment by kimtaehyeong** [comment]
> https://drive.google.com/file/d/1fw63_PCRTFulDf6jgQRCPnKPZHHoYFZ4/view?usp=sharing

Thanks for sharing the link.
However, you do not have permission to download the Google Drive link you shared. Can you give me permission ?
thank you.

**Comment by ycdhqzhiai** [comment]
@kimtaehyeong I have modified the permission. Can't you download it yet

**Comment by kimtaehyeong** [comment]
> 



> @kimtaehyeong I have modified the permission. Can't you download it yet

Yes, there is still only view right, no download right.

**Comment by ycdhqzhiai** [comment]
Sorry, you can try again

**Comment by kimtaehyeong** [comment]
> Sorry, you can try again

Download was successful. Thank you!
