### ISSUE TITLE
数据归一化

### ISSUE THREAD

**Issue by fengyanWang** [ycdhqzhiai/Gaze-PFLD#6]
你好，我看你推理部分代码没有对读入图片做数据的归一化，请问这是正常的吗？还有开源的模型效果是readme中那张图吗？期待回复，谢谢！

**Comment by ycdhqzhiai** [comment]
https://github.com/ycdhqzhiai/Gaze-PFLD/blob/2dcd284943ee34e84373b5b5215bf8b5f56fea7c/test.py#L128
这个0-1就是归一化啊

**Comment by fengyanWang** [comment]
> 这是转pytorch的tensor吧。我想知道的是减去均值除方差这种操作

**Comment by ycdhqzhiai** [comment]
你需要仔细读下代码，看看API
